name: Build Tweak

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Theos
        uses: Randomblock1/theos-action@v1
        with:
          theos-dir: 'theos'
          theos-sdk: 'iphoneos16.5'

      - name: Build Tweak
        run: |
          export THEOS=$GITHUB_WORKSPACE/theos
          make package
        env:
          REPO_NAME: ${{ github.event.repository.name }}

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: tweak-deb
          path: packages/*.deb
